########################################################
# Installation
########################################################

AGENT_UPDATE=yes
CONF_UPDATE=yes
PROJECT_ROOT=/home/ya.ryazancev/printer_hub

########################################################
# Data source
########################################################

LOG_SOURCE=journald


########################################################
# Transport
########################################################

SEND_METHOD=zabbix


########################################################
# API
########################################################

API_URL=http://192.168.1.10:8000/api/printers/report/


########################################################
# Zabbix
########################################################

ZABBIX_HOST=ois-sex.ipa.psati.ru
ZABBIX_PORT=10051

ZABBIX_ITEM_HOST=printer-server
ZABBIX_ITEM_KEY=printer.job.raw

ZABBIX_HEALTH_KEY=printer.agent.health