# Пока не используется
SERVER_URL=http://192.168.1.10:8000/api/printers/report/

#ip of zabbix machine
ZABBIX_HOST=10.0.213.163
ZABBIX_PORT=10051

#Item name at zabbix
ZABBIX_ITEM_HOST=printer-server
ZABBIX_ITEM_KEY=printer.job.raw

#healthcheck 
ZABBIX_HEALTH_KEY=printer.agent.health